version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://fsrs:fsrs_password@db:5432/fsrs_flashcards
      - FLASK_ENV=development
    depends_on:
      - db
    command: python run.py

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=fsrs
      - POSTGRES_PASSWORD=fsrs_password
      - POSTGRES_DB=fsrs_flashcards
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: